# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout/main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Biodata(object):
    def setupUi(self, Biodata):
        Biodata.setObjectName("Biodata")
        Biodata.resize(701, 289)
        self.widget = QtWidgets.QWidget(Biodata)
        self.widget.setGeometry(QtCore.QRect(10, 10, 206, 271))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditNama = QtWidgets.QLineEdit(self.widget)
        self.lineEditNama.setObjectName("lineEditNama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditNama)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditNIM = QtWidgets.QLineEdit(self.widget)
        self.lineEditNIM.setObjectName("lineEditNIM")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditNIM)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditProdi = QtWidgets.QLineEdit(self.widget)
        self.lineEditProdi.setObjectName("lineEditProdi")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditProdi)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditHobi = QtWidgets.QLineEdit(self.widget)
        self.lineEditHobi.setObjectName("lineEditHobi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditHobi)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonTambahkan = QtWidgets.QPushButton(self.widget)
        self.pushButtonTambahkan.setObjectName("pushButtonTambahkan")
        self.horizontalLayout_2.addWidget(self.pushButtonTambahkan)
        self.pushButtonHapus = QtWidgets.QPushButton(self.widget)
        self.pushButtonHapus.setObjectName("pushButtonHapus")
        self.horizontalLayout_2.addWidget(self.pushButtonHapus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Biodata)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 10, 471, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetBiodata = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidgetBiodata.setObjectName("tableWidgetBiodata")
        self.tableWidgetBiodata.setColumnCount(4)
        self.tableWidgetBiodata.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBiodata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBiodata.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBiodata.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBiodata.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidgetBiodata)
        self.labelWarning = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelWarning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelWarning.setObjectName("labelWarning")
        self.verticalLayout_2.addWidget(self.labelWarning)
        self.verticalLayoutWidget.raise_()
        self.tableWidgetBiodata.raise_()

        self.retranslateUi(Biodata)
        QtCore.QMetaObject.connectSlotsByName(Biodata)

    def retranslateUi(self, Biodata):
        _translate = QtCore.QCoreApplication.translate
        Biodata.setWindowTitle(_translate("Biodata", "Aplikasi Biodata"))
        self.label_2.setText(_translate("Biodata", "Biodata"))
        self.label.setText(_translate("Biodata", "Nama"))
        self.label_3.setText(_translate("Biodata", "NIM"))
        self.label_4.setText(_translate("Biodata", "Prodi"))
        self.label_5.setText(_translate("Biodata", "Hobi"))
        self.pushButtonTambahkan.setText(_translate("Biodata", "Tambahkan"))
        self.pushButtonHapus.setText(_translate("Biodata", "Hapus"))
        item = self.tableWidgetBiodata.horizontalHeaderItem(0)
        item.setText(_translate("Biodata", "Nama"))
        item = self.tableWidgetBiodata.horizontalHeaderItem(1)
        item.setText(_translate("Biodata", "NIM"))
        item = self.tableWidgetBiodata.horizontalHeaderItem(2)
        item.setText(_translate("Biodata", "Prodi"))
        item = self.tableWidgetBiodata.horizontalHeaderItem(3)
        item.setText(_translate("Biodata", "Hobi"))
        self.labelWarning.setText(_translate("Biodata", "warning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Biodata = QtWidgets.QWidget()
    ui = Ui_Biodata()
    ui.setupUi(Biodata)
    Biodata.show()
    sys.exit(app.exec_())

